% Auto-generated by cameraCalibrator app on 15-Aug-2022
%-------------------------------------------------------


% USE THIS SCRIPT TO UNDISTORT THE CHECKBOAD CALIBRATION CARD. 
% SAVE THE WORKSPACE RESULTS as Camera_calibration.mat

% Define images to process
imageFileNames = {
    'G:\Shared drives\TrEnT\2. Max Planck - Gecko-Inspired Textures for Surgical Grasping\UMT trial testing\Image Processing - Adhesion\Calibration checker\Distorted Split Frames\calibration_001.jpg',...
    'G:\Shared drives\TrEnT\2. Max Planck - Gecko-Inspired Textures for Surgical Grasping\UMT trial testing\Image Processing - Adhesion\Calibration checker\Distorted Split Frames\calibration_002.jpg',...
    'G:\Shared drives\TrEnT\2. Max Planck - Gecko-Inspired Textures for Surgical Grasping\UMT trial testing\Image Processing - Adhesion\Calibration checker\Distorted Split Frames\calibration_003.jpg',...
    'G:\Shared drives\TrEnT\2. Max Planck - Gecko-Inspired Textures for Surgical Grasping\UMT trial testing\Image Processing - Adhesion\Calibration checker\Distorted Split Frames\calibration_004.jpg',...
    'G:\Shared drives\TrEnT\2. Max Planck - Gecko-Inspired Textures for Surgical Grasping\UMT trial testing\Image Processing - Adhesion\Calibration checker\Distorted Split Frames\calibration_005.jpg',...
    'G:\Shared drives\TrEnT\2. Max Planck - Gecko-Inspired Textures for Surgical Grasping\UMT trial testing\Image Processing - Adhesion\Calibration checker\Distorted Split Frames\calibration_006.jpg',...
    'G:\Shared drives\TrEnT\2. Max Planck - Gecko-Inspired Textures for Surgical Grasping\UMT trial testing\Image Processing - Adhesion\Calibration checker\Distorted Split Frames\calibration_007.jpg',...
    'G:\Shared drives\TrEnT\2. Max Planck - Gecko-Inspired Textures for Surgical Grasping\UMT trial testing\Image Processing - Adhesion\Calibration checker\Distorted Split Frames\calibration_008.jpg',...
    'G:\Shared drives\TrEnT\2. Max Planck - Gecko-Inspired Textures for Surgical Grasping\UMT trial testing\Image Processing - Adhesion\Calibration checker\Distorted Split Frames\calibration_009.jpg',...
    'G:\Shared drives\TrEnT\2. Max Planck - Gecko-Inspired Textures for Surgical Grasping\UMT trial testing\Image Processing - Adhesion\Calibration checker\Distorted Split Frames\calibration_010.jpg',...
    'G:\Shared drives\TrEnT\2. Max Planck - Gecko-Inspired Textures for Surgical Grasping\UMT trial testing\Image Processing - Adhesion\Calibration checker\Distorted Split Frames\calibration_011.jpg',...
    'G:\Shared drives\TrEnT\2. Max Planck - Gecko-Inspired Textures for Surgical Grasping\UMT trial testing\Image Processing - Adhesion\Calibration checker\Distorted Split Frames\calibration_012.jpg',...
    };
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 1;  % in units of 'millimeters'
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure(1); showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure(2); showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
